package com.loischsiy.rotpspin.client.render;

import java.util.List;

import com.loischsiy.rotpspin.AddonMain;
import com.loischsiy.rotpspin.entity.SteelBallEntity;
import com.loischsiy.rotpspin.entity.WreckingBall;
import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.IRenderTypeBuffer;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.EntityRenderer;
import net.minecraft.client.renderer.entity.EntityRendererManager;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.client.renderer.texture.NativeImage;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.vector.Matrix3f;
import net.minecraft.util.math.vector.Matrix4f;
import net.minecraft.util.math.vector.Quaternion;
import net.minecraft.util.math.vector.Vector3d;
import net.minecraft.util.math.vector.Vector3f;

/**
 * A spinning ball is an exact math sphere with a procedural wraparound skin, rotating around the
 * axis perpendicular to the flight — like a rolling wheel. No billboard sprite: the rotation reads
 * from every camera angle. The Steel Ball is a green metal sphere with a hexagonal plate and curved
 * slits (PNG wrap); the Wrecking Ball is a dark copper sphere with orange grooves and 14
 * gold satellites seated on a golden-angle lattice; once they fly out only dark sockets remain.
 */
public class SteelBallRenderer extends EntityRenderer<SteelBallEntity> {
    private static final float RADIUS = 0.19F;
    // Visual only, not gameplay: the sphere reads better slightly bigger than the hitbox.
    private static final SpinSphere MESH = SpinSphere.build(RADIUS, 24, 16);
    // A satellite in flight is the seated ball scaled up a little, so it stays readable at speed.
    private static final float SATELLITE_RADIUS = 0.055F;
    private static final float SATELLITE_SCALE = 0.4F;
    private static final SpinSphere SATELLITE_MESH = SpinSphere.build(SATELLITE_RADIUS, 12, 8);
    // Where the satellite centres sit, as a fraction of the body radius: a gold dome above the
    // surface; the empty socket is a dark dent slightly sunk into it.
    private static final float SEATED_DEPTH = 0.98F;
    private static final float EMPTY_DEPTH = 0.96F;
    private static final List<Vector3d> SOCKETS = WreckingBall.socketDirections(WreckingBall.SATELLITE_COUNT);
    private static final float DEGREES_PER_TICK = 40.0F;

    // Green Steel Ball wrap (256x128 equirect) generated by docs/art/tools/gen_steel_ball.py.
    private static final ResourceLocation STEEL_TEXTURE =
            new ResourceLocation(AddonMain.MOD_ID, "textures/entity/steel_ball_wrapped.png");
    private ResourceLocation wreckingTexture;
    private ResourceLocation satelliteTexture;
    private ResourceLocation socketTexture;

    public SteelBallRenderer(EntityRendererManager manager) {
        super(manager);
    }

    @Override
    public void render(SteelBallEntity entity, float yaw, float partialTicks, MatrixStack matrixStack,
            IRenderTypeBuffer buffer, int packedLight) {
        boolean satellite = entity.isSatellite();
        matrixStack.pushPose();
        float scale = satellite ? SATELLITE_SCALE : 1.0F;
        matrixStack.scale(scale, scale, scale);
        matrixStack.mulPose(spinRotation(entity, partialTicks));

        drawMesh(buffer, texture(entity), matrixStack, MESH, packedLight);
        if (entity.isWrecking() && !satellite) {
            boolean empty = entity.areSatellitesReleased();
            ResourceLocation seatTexture = empty ? socketTexture() : satelliteTexture();
            float depth = RADIUS * (empty ? EMPTY_DEPTH : SEATED_DEPTH);
            for (Vector3d direction : SOCKETS) {
                matrixStack.pushPose();
                matrixStack.translate(direction.x * depth, direction.y * depth, direction.z * depth);
                drawMesh(buffer, seatTexture, matrixStack, SATELLITE_MESH, packedLight);
                matrixStack.popPose();
            }
        }
        matrixStack.popPose();
        super.render(entity, yaw, partialTicks, matrixStack, buffer, packedLight);
    }

    private static void drawMesh(IRenderTypeBuffer buffer, ResourceLocation texture, MatrixStack matrixStack,
            SpinSphere mesh, int packedLight) {
        IVertexBuilder builder = buffer.getBuffer(RenderType.entityCutoutNoCull(texture));
        Matrix4f pose = matrixStack.last().pose();
        Matrix3f normal = matrixStack.last().normal();
        int[] indices = mesh.indices;
        float[] positions = mesh.positions;
        float[] normals = mesh.normals;
        float[] uvs = mesh.uvs;
        for (int i = 0; i < indices.length; i++) {
            int v = indices[i];
            builder.vertex(pose, positions[v * 3], positions[v * 3 + 1], positions[v * 3 + 2])
                    .color(255, 255, 255, 255)
                    .uv(uvs[v * 2], uvs[v * 2 + 1])
                    .overlayCoords(OverlayTexture.NO_OVERLAY)
                    .uv2(packedLight)
                    .normal(normal, normals[v * 3], normals[v * 3 + 1], normals[v * 3 + 2])
                    .endVertex();
        }
    }

    /** Spin around the axis perpendicular to the velocity, like a rolling wheel. */
    static Quaternion spinRotation(SteelBallEntity entity, float partialTicks) {
        Vector3d velocity = entity.getDeltaMovement();
        return new Quaternion(spinAxis(velocity.x, velocity.z),
                (entity.tickCount + partialTicks) * DEGREES_PER_TICK, true);
    }

    /**
     * Horizontal axis perpendicular to the flight ({@code velocity x up}), unit length.
     * Pure math for tests: straight up/down flight falls back to the X axis.
     */
    static Vector3f spinAxis(double velocityX, double velocityZ) {
        float axisX = (float) -velocityZ;
        float axisZ = (float) velocityX;
        float length = (float) Math.sqrt(axisX * axisX + axisZ * axisZ);
        if (length < 1e-4F) {
            return new Vector3f(1.0F, 0.0F, 0.0F);
        }
        return new Vector3f(axisX / length, 0.0F, axisZ / length);
    }

    private ResourceLocation texture(SteelBallEntity entity) {
        if (entity.isSatellite()) {
            return satelliteTexture();
        }
        if (entity.isWrecking()) {
            if (wreckingTexture == null) {
                wreckingTexture = register("wrecking_ball_sphere", SpinSphereTexture.wreckingBall());
            }
            return wreckingTexture;
        }
        return STEEL_TEXTURE;
    }

    private ResourceLocation satelliteTexture() {
        if (satelliteTexture == null) {
            satelliteTexture = register("wrecking_satellite_sphere", SpinSphereTexture.satelliteBall());
        }
        return satelliteTexture;
    }

    private ResourceLocation socketTexture() {
        if (socketTexture == null) {
            socketTexture = register("wrecking_socket_sphere", SpinSphereTexture.emptySocket());
        }
        return socketTexture;
    }

    private static ResourceLocation register(String name, NativeImage image) {
        ResourceLocation location = new ResourceLocation(AddonMain.MOD_ID, "dynamic/" + name);
        Minecraft.getInstance().getTextureManager().register(location, new DynamicTexture(image));
        return location;
    }

    @Override
    public ResourceLocation getTextureLocation(SteelBallEntity entity) {
        return texture(entity);
    }
}
